[book]
title = "amaker User Manual"
authors = ["Como Technologies"]
language = "en"
src = "src"

[build]
build-dir = "../target/book"

[output.html]
git-repository-url = "https://github.com/como-technologies/taps"
edit-url-template = "https://github.com/como-technologies/taps/edit/main/assessments/docs/{path}"
