//! The `docusaurus` target: a Docusaurus `docs/` tree — pages carry YAML front
//! matter (`title` / `sidebar_position`) with the H1 dropped, an `intro.md`
//! landing, and each category folder gets a `_category_.json` so the sidebar is
//! autogenerated.

use std::path::PathBuf;

use super::{OutputFile, PageCtx, PublishModel, PublishedAdr, Publisher, category_segment, quote};

pub struct Docusaurus;

impl Publisher for Docusaurus {
    fn page_path(&self, adr: &PublishedAdr) -> PathBuf {
        match category_segment(adr) {
            Some(cat) => PathBuf::from(format!("docs/{cat}/{}.md", adr.slug)),
            None => PathBuf::from(format!("docs/{}.md", adr.slug)),
        }
    }

    fn render_page(&self, ctx: &PageCtx) -> String {
        let mut page = String::from("---\n");
        page.push_str(&format!("title: {}\n", quote(&ctx.adr.title)));
        page.push_str(&format!("sidebar_position: {}\n", ctx.order + 1));
        page.push_str("---\n\n");
        page.push_str(ctx.body);
        page
    }

    fn aux_files(&self, model: &PublishModel, _pages: &[PathBuf]) -> Vec<OutputFile> {
        let mut files = vec![OutputFile {
            path: PathBuf::from("docs/intro.md"),
            contents:
                "---\ntitle: Decision Log\nsidebar_position: 0\n---\n\nAccepted architecture decisions.\n"
                    .to_string(),
        }];
        for (n, section) in model.sections.iter().enumerate() {
            if let Some(name) = &section.name {
                let cat = crate::naming::slugify(name);
                files.push(OutputFile {
                    path: PathBuf::from(format!("docs/{cat}/_category_.json")),
                    contents: format!(
                        "{{\n  \"label\": {},\n  \"position\": {}\n}}\n",
                        quote(name),
                        n + 1
                    ),
                });
            }
        }
        files
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::publish::{strip_h1, test_model};
    use std::path::Path;

    #[test]
    fn front_matter_and_category_json() {
        let m = test_model(true);
        let body = strip_h1(&m.adrs[1].raw);
        let ctx = PageCtx {
            adr: &m.adrs[1],
            order: 1,
            raw: &m.adrs[1].raw,
            body: &body,
        };
        let page = Docusaurus.render_page(&ctx);
        assert!(page.contains("title: \"Hexagonal architecture\""));
        assert!(page.contains("sidebar_position: 2"));
        let aux = Docusaurus.aux_files(&m, &[]);
        let cat = aux
            .iter()
            .find(|f| f.path == Path::new("docs/arch/_category_.json"))
            .unwrap();
        assert!(
            cat.contents.contains("\"label\": \"arch\""),
            "{}",
            cat.contents
        );
    }
}
